### ISSUE TITLE
Critical Error [Forge 1.20.1, ArcLight, forge 47.3.0]

### ISSUE THREAD

**Issue by PhobosStarlight** [Suiranoil/SkinRestorer#35]
After a long time searching through the mods, this is the one that causes the error, it does not let me enter the server and I get the error on the screen

"org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

my modlist:
Farmer's Delight, Combat Roll, Terralith, Clumps, HT's TreeChop, Cloth Config v10 API, Moonlight Library, Supplementaries, Explorer's Compass, Regions Unexplored, Tom's Simple Storage Mod, Create, Palladium, EntityCulling, Supplementaries Squared, Carry On, Ksyxis, Nature's Compass, Icterine, Create: Less Ticking, TerraBlender, Get It Together, Drops!, Starlight, Noisium, ImmediatelyFast, Collective, Ferrite Core, Amendments, Balm, Player Animator, ToadLib, Ore Harvester, Saturn, Emotecraft, TrashSlot, Lithostitched, ChoiceTheorem's Overhauled Village.

Forge 1.20.1, ver: 47.3.0
Arclight

**Comment by PhobosStarlight** [comment]
Server debug log:
[debug.log](https://github.com/user-attachments/files/17087807/debug.log)
Client Debug Log:
[debug.log](https://github.com/user-attachments/files/17087808/debug.log)

**Comment by Suiranoil** [comment]
So issue seems to be related to Arclight overwriting `handleAcceptedLogin` method with mixins: https://github.com/IzzelAliz/Arclight/blob/b2cde4af80aee0e192380fc878f450608dba6cd7/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/network/ServerLoginNetHandlerMixin.java#L76C5-L117C6
My mod tries to inject itself into the same method at `canPlayerLogin` which is no longer present in Arclight version:
https://github.com/Suiranoil/SkinRestorer/blob/9c9907d0ba41077fc84a78a2295c1803a1adc7eb/common/src/main/java/net/lionarius/skinrestorer/mixin/ServerLoginPacketListenerImplMixin.java#L29-L32

Since Arclight aims to suport craftbukkit you could try to use SkinsRestorer plugin: https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by PhobosStarlight** [comment]
Is there any way to fix this or is it impossible? Thank you very much for your attention, it would be good to warn that the mod is incompatible with arclight if it cannot be solved.

**Comment by PhobosStarlight** [comment]
:(
